name: Deploy AuditTrail

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      LOG_SIGNING_KEY: ${{ secrets.LOG_SIGNING_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          TEST_DEBUG=True python manage.py test logger.tests

      - name: Build and push Docker images
        run: |
          docker build -t audittrail-app:latest .
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker tag audittrail-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/audittrail-app:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/audittrail-app:latest

      - name: Deploy to Docker Swarm
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            docker service rm audittrail_app || true
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/audittrail-app:latest
            docker stack deploy -c docker-compose.yml audittrail
          "

    env:
      DOCKER_BUILDKIT: 1