name: Deploy AuditTrail

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      LOG_SIGNING_KEY: ${{ secrets.LOG_SIGNING_KEY }}
      MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Start MongoDB and Redis with Docker Compose
        run: |
          docker-compose up -d mongo redis
          # Wait for services to be ready
          sleep 10

      - name: Run tests
        run: |
          export MONGO_URI="mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@localhost:27017/audittrail_db?authSource=admin"
          export CELERY_BROKER_URL="redis://localhost:6379/0"
          export CELERY_RESULT_BACKEND="redis://localhost:6379/0"
          export LOG_SIGNING_KEY=${LOG_SIGNING_KEY}
          TEST_DEBUG=True python manage.py test logger.tests

      - name: Build and push Docker images
        run: |
          docker build -t audittrail-app:latest .
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker tag audittrail-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/audittrail-app:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/audittrail-app:latest

      - name: Configure SSH for deployment
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          # Add SSH private key from secret
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Docker Swarm
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            docker service rm audittrail_app || true
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/audittrail-app:latest
            docker stack deploy -c docker-compose.yml audittrail
          "